### ISSUE TITLE
Update Docusaurus config to launch settings

### ISSUE THREAD

**Issue by Pabl0cks** [scaffold-eth/se2-docs#4]
We need to tweak `docusaurus.config.js` to clean up some default docusaurus assets/links, and set the navigation bar and footer links.

I've just pushed a initial version to the PR #3 so we can iterate from there.

```[tasklist]
### Tasks
- [X] Set navigation bar menu.
- [X] Setup editUrl so it opens the file you want to edit on the repo.
- [X] Delete default docusaurus-social-card.jpg => Changed to SE2 thumbnail for now.
- [X] Set footer menu. 
```

**Comment by carletex** [comment]
Hey @Pabl0cks , can you elaborate a bit more on what is this about?
